version: 0.0
os: windows
files:
  - source: \
    destination: C:\temp\wwwroot\00010358
hooks:
  BeforeInstall:
    - location: \deletewebsite.bat
      timeout: 180
  AfterInstall:
    - location: \installwebsite.bat
      timeout: 180